default_platform(:ios)

platform :ios do
  def app_store_connect_api_key
    app_store_connect_api_key(
      key_id: ENV["APPSTORE_API_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_content: ENV["APPSTORE_API_PRIVATE_KEY"],
      in_house: false
    )
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store"
    )

    upload_to_testflight(
      api_key: app_store_connect_api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
